### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by jianing-sun** [MarcBS/food_localization_recognition#1]
When I execute `locNet = loadStagedModel(params['model_loc_path'])` in the demo.py, it returns me with this error:
`Traceback (most recent call last):
  File "/Users/jianingsun/Documents/Research/May/JN/0524.py", line 78, in <module>
    locNet = loadStagedModel(params['model_loc_path'])
  File "/Users/jianingsun/Documents/Research/May/JN/keras_wrapper/deprecated/staged_network.py", line 143, in loadStagedModel
    model = model_from_json(open(path_stage + '/Stage_structure.json'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/keras/models.py", line 350, in model_from_json
    config = json.load(json_string)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

What's the problem with the json file?

**Comment by MarcBS** [comment]
Did you make sure that the model is correctly located in that folder?
By default it is in `model_loc_path = 'Final_Models/recognition/GoogleNet_FoodVsNoFood_GAP'`

**Comment by jianing-sun** [comment]
@MarcBS Hi! Thanks a lot for your reply. I'm pretty sure that the model is loaded in the corresponding folder. The problem occurs when the program read the .json file. 
The problematic statement is `model = model_from_json(open(path_stage + '/Stage_structure.json')) File` in the `staged_network.py`. Can you try to read the json file to see if there is a problem?
Thanks!
